## NumPy
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array
object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays,
including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic
statistical operations, random simulation and much more.
At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types.

- It is a datatype which is based on C but can be used in Python. 

### NumPy arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

- NumPy arrays are mutable, but has a fixed memory size


In [4]:
#Creating a NumPy object

import numpy as np

print(np.array([1,4,2]))
print(type(np.array([4,7,2])))

[1 4 2]
<class 'numpy.ndarray'>


In [7]:
#Creating a 2D array

print(np.array([[2,1,5],[7,5,1]]))  #We can call it as a matrix as well, because the structures is very similar to that of matrix.

[[2 1 5]
 [7 5 1]]


In [9]:
#3D Array

print(np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]]))  #The 3D array is known as the Tensor

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [12]:
#Differnet datatypes of ndarray

print(np.array([3,1,5],dtype=float))
print(np.array([3,1,5],dtype=complex))
print(np.array([3,1,5],dtype=str))

[3. 1. 5.]
[3.+0.j 1.+0.j 5.+0.j]
['3' '1' '5']


In [15]:
#Range function of NumPy array

print(np.arange(10,15))
print(np.arange(1,8,2))

[10 11 12 13 14]
[1 3 5 7]


In [27]:
#Reshape
a=np.arange(1,21).reshape(10,2)  #The product of of x and y should be equal to the number of items present inside array.
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [29]:
a=np.arange(1,21).reshape(2,10)
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [30]:
a=np.arange(1,16).reshape(5,3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [42]:
a=np.arange(1,21).reshape(2,2,5)
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [31]:
np.ones((2,4))  # It will create an array of element 1
#Use case, sometimes we do weight initialization in Neural Netwroks 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [229]:
#Random
import random
np.random.random((4,3))

array([[0.46240212, 0.49411312, 0.04205376],
       [0.24706075, 0.24183444, 0.10237305],
       [0.98751253, 0.78854817, 0.82521146],
       [0.26892885, 0.990481  , 0.90682827]])

In [40]:
#Linspace : In Linspace we have to provide the range first, start and stop. Then the third parameter is how many numbers 
#we want from that range. Also, one of the important thing about linspace is the numbers it generated if we subtract any of the two numbers
#it will always give the same result. For example- -10 - (-8.571) = x which is same as -2.8571 -(-1.4285) = x

print(np.linspace(-10,10,15))
print(np.linspace(-10,10,15,dtype=int))

[-10.          -8.57142857  -7.14285714  -5.71428571  -4.28571429
  -2.85714286  -1.42857143   0.           1.42857143   2.85714286
   4.28571429   5.71428571   7.14285714   8.57142857  10.        ]
[-10  -9  -8  -6  -5  -3  -2   0   1   2   4   5   7   8  10]


In [43]:
#Identity Matrix

print(np.identity(4))  #Identity matrix is a type of matrix which has the identical diagonal

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [46]:
a=np.arange(1,8)
b=np.arange(1,11,dtype=float).reshape(2,5)
c=np.arange(1,21).reshape(2,2,5)

In [51]:
#ndim -> Tells the number of dimensions 

print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


In [55]:
#Shape
print(a.shape)
print(b.shape)
print(c.shape)

(7,)
(2, 5)
(2, 2, 5)


In [57]:
#Size

print(a.size)
print(b.size)
print(c.size)

7
10
20


In [60]:
#itemsize

print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

#Normally item size of int and float is different. But if we are using the Jupyter or Collab notebook, they assign the 8 byte value 
#to both int and float

#But if we check the same thing in Pycharm, it will show the different value.

8
8
8


In [67]:
#Changing the size the int. We have two different types of int 32-bit and 64-bit. By default it is 64-bit in collab and Jupyter notebook

a=np.arange(1,8,dtype=np.int32)  #Changing the size of integer.
print(a.itemsize)  #This item size is the memory taken by each item.

4


In [68]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int64


In [81]:
#Another way of changing the size of datatype is:

a=np.arange(1,8,dtype=np.int32)

a=a.astype(dtype=np.int64)  #Very Important thing to remember. NumPy arrays has fixed memory size. Hence, we can only change the size of array while
#creating them. astype() will not change the size. Instead it will create a new array.
#Here a=a means we are creating a new array using aliasing 
print(a.dtype)  #This is a new array

int64


#### Operations of Arrays

In [88]:
a1=np.arange(1,16,dtype=np.int32).reshape(3,5)
a2=np.arange(15,30,dtype=np.int32).reshape(3,5)

print(a1)
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [87]:
#Scaler Operation
print(a1*2) #where a1 is the matrix and 2 is the scaler

[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


In [89]:
print(a1**2)

[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]]


In [90]:
print(a1+10)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [92]:
print(a1-10)

[[-9 -8 -7 -6 -5]
 [-4 -3 -2 -1  0]
 [ 1  2  3  4  5]]


In [93]:
print(a1/10)

[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]
 [1.1 1.2 1.3 1.4 1.5]]


In [94]:
print(a1>5)

[[False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [108]:
a1=np.arange(1,16,dtype=np.int32).reshape(3,5)
print(a1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [112]:
#sum/min/max/prod
print(a1.sum())
print(a1.prod())
print(a1.min())
print(a1.max())


120
1307674368000
1
15


In [115]:
#Another method
print(np.sum(a1))
print(np.min(a1))
print(np.max(a1))
print(np.prod(a1))

120
1
15
1307674368000


#### The difference b/w a.sum() and np.sum(a)
The difference b/w both the methods is: a1. is calling the method of the Numpy class. Where is np.sum is more generic. np.sum can
be used on lists as well. Where as a1.sum() will only support the Numpy objects. 

In [119]:
#For a particular row or column

a1=np.arange(1,16,dtype=np.int32).reshape(3,5)
print(a1)

#Remember 0 is column and 1 is row
print(np.sum(a1,axis=1))
print(np.sum(a1,axis=0))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[15 40 65]
[18 21 24 27 30]


In [122]:
#Mean, Median, STD, Variance

print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

8.0
8.0
4.320493798938574
18.666666666666668


In [127]:
print(np.std(a1,axis=0))
print("\n")
print(np.var(a1,axis=1))

[4.0824829 4.0824829 4.0824829 4.0824829 4.0824829]


[2. 2. 2.]


In [3]:
a1=np.arange(1,16,dtype=np.int32).reshape(3,5)
a2=np.arange(15,30,dtype=np.int32).reshape(5,3)
print(np.dot(a1,a2))

[[ 345  360  375]
 [ 870  910  950]
 [1395 1460 1525]]


In [4]:
#log and Exponential
import numpy as np
print(np.log(a1))  #We don't have any axis here because log and expo operations are performend on every single element
print("\n")
print(np.exp(a1))

[[0.         0.69314718 1.09861229 1.38629436 1.60943791]
 [1.79175947 1.94591015 2.07944154 2.19722458 2.30258509]
 [2.39789527 2.48490665 2.56494936 2.63905733 2.7080502 ]]


[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
  1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03 8.10308393e+03
  2.20264658e+04]
 [5.98741417e+04 1.62754791e+05 4.42413392e+05 1.20260428e+06
  3.26901737e+06]]


In [140]:
#round,ceil,floor

print(np.round(np.log(a1),4))
print(np.ceil(np.log(a1)))
print(np.floor(np.log(a1)))

[[0.     0.6931 1.0986 1.3863 1.6094]
 [1.7918 1.9459 2.0794 2.1972 2.3026]
 [2.3979 2.4849 2.5649 2.6391 2.7081]]
[[0. 1. 2. 2. 2.]
 [2. 2. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
[[0. 0. 1. 1. 1.]
 [1. 1. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [143]:
#Indexing and Slicing 

a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [145]:
print(a[-1])
print(a[0])
print(a[4])

10
1
5


In [146]:
a1=np.arange(1,16,dtype=np.int32).reshape(5,3)
print(a1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [149]:
#5
print(a1[1,1])
#12
print(a1[3,2]) #first we have the write the row and then the column. 

5
12


In [150]:
a2=np.arange(1,21).reshape(2,5,2)
print(a2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


In [152]:
#10
print(a2[0,4,1])
#11
print(a2[1,0,0])
#15
print(a2[1,2,0])  #First we have to type the block. In our 3d array we have 2 blocks and in each block we have 5 rows and for rows we have 2 columns

10
11
15


In [153]:
#Slicing 
a1=np.arange(1,16,dtype=np.int32).reshape(5,3)
print(a1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
a=np.arange(1,11)
print(a)

In [158]:
#If I want the second row i.e. 7,8,9
print(a1[2,:])

#If I want the top row i.e 1,2,3
print(a1[0,:])

#The : means all the columns. First we are asking for the rows and the we are asking for the columns. We want all the columns hence :

[7 8 9]
[1 2 3]


In [161]:
#If I want 3rd column i.e. 3,6,9,12,15
print(a1[:,2])

#If I want the 1st column i.e. 1,4,7,10,13
print(a1[:,0])

[ 3  6  9 12 15]
[ 1  4  7 10 13]


In [164]:
#If I want the elements 4,5,7,8
print(a1[1:3,0:2])

print("\n")
#If I want the elements 8,9,11,12
print(a1[2:4,1:])

[[4 5]
 [7 8]]


[[ 8  9]
 [11 12]]


In [166]:
a=np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [167]:
a1=np.arange(1,16,dtype=np.int32).reshape(5,3)
print(a1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [172]:
#A really good example
#If I want the numbers 1,3,13,15
print(a1[::4,::2])   
#Over here as we want the first and last row, so for that we need all the rows that is why we have :: and then step of 4, to 
#get the last row.
#For columns as well, we need the first and the last column, means we need all the columns, hence :: and then step of 2

[[ 1  3]
 [13 15]]


In [174]:
a2=np.arange(1,13).reshape(3,4)
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [175]:
#If I want 2,4,10,12

print(a2[::2,1::2])

[[ 2  4]
 [10 12]]


In [176]:
#If I want only 5 and 8
print(a2[1:2,::3])

[[5 8]]


In [177]:
#If I want 6,7,8
print(a2[1,1:])

[6 7 8]


In [178]:
#3D Array

a3=np.arange(27).reshape(3,3,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [179]:
#If I want num=20
print(a3[2,0,2])

20


In [180]:
#If I want the middle block whole
print(a3[1,:,:])

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [196]:
#If I want 18,20,24,26
print(a3[2,::2,::2])

[[18 20]
 [24 26]]


In [197]:
#Very Important Question
#If I want 0,2,18,20
print(a3[0::2,::4,::2])

[[[ 0  2]]

 [[18 20]]]


In [201]:
#If I want 3,5,21,23
print(a3[::2,1::2,::2])

[[[ 3  5]]

 [[21 23]]]


In [10]:
a3=np.arange(27).reshape(3,3,3)
print(a3)
#[6 7 8]
#[15 16 17] 
print("\n")
print(a3[0:2,2,:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[[ 6  7  8]
 [15 16 17]]


In [8]:
#If I want 6,8,9,11  #We can do this using the fancy Indexing as we cannot use the slicing
#In facy indexing first we have to find out the coordinate of individual element.
#for 6
print(a3[0,2,0])
#for 8
print(a3[0,2,2])
#for 9
print(a3[1,0,0])
#for 11
print(a3[1,0,2])

#Now we will apply the fancy indexing
value=a3[       
    [0,0,1,1],
    [2,2,0,0],
    [0,2,0,2]
    ]      
#The first array [0,0,1,1] Talks about the blocks. [2,2,0,0] talks about the rows, [0,2,0,2] talks about columns
print(value)

6
8
9
11
[ 6  8  9 11]


In [16]:
#If I want 6,8,9,11
#Another very important method for Tensor (3D) if we want the result in 2d rather than 1D
value=a3[
    [0,1],
    [2,0],
    :3
]
print(value)

[[ 6  7  8]
 [ 9 10 11]]


In [206]:
print(a)
for i in a:
    print(i)

[1 3 5 7 9]
1
3
5
7
9


In [213]:
#print(a2)
#print("\n")

for i in a2:   
    print(i)   #For 2d array For loop will print the each row

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


In [215]:
#print(a3)
#print("\n")

for i in a3:
    print(i)  #For 3d array For loop will print each 2d array

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [216]:
#If we want every single element from the 3d array

for i in a3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [217]:
#Or we can use the in-build function

for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [224]:
#Transpose

print(a2)
print("\n")
print(a2.T)  #Method - 1
print("\n")
print(np.transpose(a2))   #Method - 2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [227]:
#Ravel - This method convert the 2d or 3d or n-d array into 1-d array
print(a3)
print("\n")
print(np.ravel(a3))  

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


#### Stacking - It is of two types 
- Horizontal Stacking
- Vertical Stacking

1. Horizontal Stacking - If we have two arrays of 2D shape (2x2) , (2x2) and if we do horizontal stacking then, the new array will be (2x4). (x-axis)
2. Vertical Stacking - If we have two arrays of 2D shape (2x2) , (2x2) and if we do vertical stacking then, the new array will be (4x2). (y-axis)

#### It is important to know that shape should be same for both the matrix in order to do stacking

In [234]:
print(a2)
a12=np.arange(12,24).reshape(3,4)
print("\n")
print(a12)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [237]:
print(np.hstack((a2,a12)))  #Horizontal Stack

[[ 1  2  3  4 12 13 14 15]
 [ 5  6  7  8 16 17 18 19]
 [ 9 10 11 12 20 21 22 23]]


In [239]:
print(np.hstack((a2,a12,a2)))   #In this way we can stack multiple matrix

[[ 1  2  3  4 12 13 14 15  1  2  3  4]
 [ 5  6  7  8 16 17 18 19  5  6  7  8]
 [ 9 10 11 12 20 21 22 23  9 10 11 12]]


In [241]:
#Vertical Stacking

print(np.vstack((a2,a12,a2)))  #Stacking the matrix vertically

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


#### Splitting - It is also of two types
- Horizontal Splitting
- Vertical Splitting

1. Horizontal Splitting - In horizontal splitting, we split the matrix like this |. Kind of opposite of Horizontal Stacking. (y axis)
2. Vertical Splitting - In vertical splitting, we split the matrix like this -- . Kind of opposite of Vertical Stacking. (x axis)

#### Also, it is important to know that splitting can be only done on equal parts, or else python will raise an error.

In [242]:
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [243]:
print(np.hsplit(a2,2))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [244]:
print(np.hsplit(a2,4))
#print(np.hsplit(a2,3))  #This will throw an error because we are doing horizontal splitting means splitting like 
#this | from the y axis

[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]


In [246]:
print(np.vsplit(a2,3))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [ ]:
#print(np.vsplit(a2,2)) This will again thow an error because we are doing the vertical splitting means like this --,
#And along (x axis) we can only split it in 3 equal parts.