### Numpy Functions

In [1]:
import numpy as np

In [7]:
#Sort
a=np.array([1,8,3,6,2,9,5])

print(np.sort(a))
print(np.sort(a,kind="quicksort"))
print(np.sort(a,kind="mergesort")) #Kind provide us the option to chooese different types of sort

[1 2 3 5 6 8 9]
[1 2 3 5 6 8 9]
[1 2 3 5 6 8 9]


In [13]:
a=np.random.randint(1,100,12).reshape(4,3)
print(a)
print("\n")
print(np.sort(a,axis=0))  #Column wise sort
print("\n")
print(np.sort(a,axis=1))  #Row wise sort

[[97 81 28]
 [44 78 78]
 [14 73 97]
 [99 52 34]]


[[14 52 28]
 [44 73 34]
 [97 78 78]
 [99 81 97]]


[[28 81 97]
 [44 78 78]
 [14 73 97]
 [34 52 99]]


In [19]:
#Append
a=np.array([1,8,3,6,2,9,5])
b=np.append(a,50)   #Append does not change the original array.
print(b)

[ 1  8  3  6  2  9  5 50]


In [27]:
b=np.array([[12, 52, 42, 6],
        [29, 18, 47, 55],
        [61, 93, 83, 9],
        [38, 63, 44, 85],
        [ 8, 87, 31, 72],
        [40, 71, 2, 7]])

c=np.append(b,np.zeros(shape=(np.shape(b)[0],1)),axis=1)
print(c)

[[12. 52. 42.  6.  0.]
 [29. 18. 47. 55.  0.]
 [61. 93. 83.  9.  0.]
 [38. 63. 44. 85.  0.]
 [ 8. 87. 31. 72.  0.]
 [40. 71.  2.  7.  0.]]


In [32]:
#Concatenate 
c=np.arange(1,7).reshape(2,3)
d=np.arange(7,13).reshape(2,3)
print(np.concatenate((c,d),axis=1))
print("\n")
print(np.concatenate((c,d),axis=0))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
#Unique

a=[1,5,2,3,1,4,5,3,6,6]
np.unique(a)   #Returns the unique value

array([1, 2, 3, 4, 5, 6])

In [36]:
b=np.array([[12, 52, 42, 6],
        [12, 18, 52, 55],
        [61, 93, 83, 93],
        [38, 61, 44, 85],
        [ 87, 87, 31, 2],
        [44, 71, 2, 7]])

np.unique(b)

array([ 2,  6,  7, 12, 18, 31, 38, 42, 44, 52, 55, 61, 71, 83, 85, 87, 93])

In [45]:
#expand_dims

a=np.arange(1,13)
print(np.shape(a))

b=np.expand_dims(a,axis=0)  
print(np.shape(b))

c=np.expand_dims(a,axis=1)
print(np.shape(c))

#Important - expand_dims does NOT add rows or columns — it inserts a 1 at the given index in the shape (tuple).

(12,)
(1, 12)
(12, 1)


In [51]:
a=np.random.randint(1,100,20)
print(a)

#If I want all the numbers greater than 50

print(np.where(a>50))   #It provides the index positions. Not the values

[80 23 72 87 41 92 95 68 96 97 97 12 61 33 44  5 14 39 55 60]
(array([ 0,  2,  3,  5,  6,  7,  8,  9, 10, 12, 18, 19]),)


In [54]:
#If I want to replace all the numbers greater than 50
a=np.random.randint(1,100,20)
print(a)

print(np.where(a>50,0,a))  #It require 3 things, (condition, if true then, if false then)
#In our code we are saying if a>50, the n put 0 if not then the same no.

[41 61 93 49 40 97 30 52 76 14 73 36 46 59  2 58  7 54 32 22]
[41  0  0 49 40  0 30  0  0 14  0 36 46  0  2  0  7  0 32 22]


In [57]:
#cumsum

a=np.arange(1,21)
print(np.cumsum(a)) #The cumsum returns the cumulative 

[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]


In [56]:
a=np.arange(1,21)
print(np.cumprod(a))  #It returns the cumulative product

[                  1                   2                   6
                  24                 120                 720
                5040               40320              362880
             3628800            39916800           479001600
          6227020800         87178291200       1307674368000
      20922789888000     355687428096000    6402373705728000
  121645100408832000 2432902008176640000]


In [60]:
#percentile

a=np.random.randint(1,100,20)
print(a)
np.percentile(a,98)  
#Percentile can be explained using the example- Let's say someone got 96 percentile in their result
#it means that person is ahead of 96% of the people. 
#In our result we got 83.24 percentile, it means our num 98 is ahead of 83.24 percent of the numbers.

[78 88 95 95 38  7 70 23 69 44 68 94 37 53 70 10 82 60 14 87]


np.float64(95.0)

In [63]:
#median
a=np.random.randint(1,100,20)
print(a)

print(np.median(a))

[54 84 79 97  3 88 83 30  5 76 29 44  9 59 90  9 31 90 82 75]
67.0


In [106]:
#Histogram

a=np.random.randint(1,100,20)
print(a)

np.histogram(a,bins=[0,10,20,30,40])  #I kind of created the buckets, now np.histogran will check which number 
#belong to which bucket and how many times.



[89 86 85 12 29 36 85  2 98 42 21 92 81 40 74 56 33 97 46 48]


(array([1, 1, 2, 3]), array([ 0, 10, 20, 30, 40]))

In [73]:
#corrcoef

salary=np.array([40000,20000,75000,14000,1000000])
experience=np.array([1,2,3,4,5])
np.corrcoef(salary,experience)

#+1 means strong positive correlation. -1 means strong negative correlation.

array([[1.        , 0.70180984],
       [0.70180984, 1.        ]])

In [77]:
#isin

#If we have two arrays, the isin function will tell whether the a number in one array present in another
#array or not.

a=np.random.randint(1,40,20)
print(a)
print("\n")
b=np.array([10,15,20,25,30,35,40,45,50])
print(b)
print("\n")
print(np.isin(a,b))
a[np.isin(a,b)]

[38 31  5 19 31 38  9 36 19  2 15 32  2 27 10  8 18  5 34 17]


[10 15 20 25 30 35 40 45 50]


[False False False False False False False False False False  True False
 False False  True False False False False False]


array([15, 10], dtype=int32)

In [78]:
#flip -> Flip function flip the array in opposite direction
b=np.array([10,15,20,25,30,35,40,45,50])
print(b)
print("\n")
print(np.flip(b))


[10 15 20 25 30 35 40 45 50]


[50 45 40 35 30 25 20 15 10]


In [82]:
b=np.array([[12, 52, 42, 6],
        [12, 18, 52, 55],
        [61, 93, 83, 93],
        [38, 61, 44, 85],
        [ 87, 87, 31, 2],
        [44, 71, 2, 7]])

print(np.flip(b))    #Flip both column wise and row wise
print("\n")
print(np.flip(b,axis=0))
print("\n")
print(np.flip(b,axis=1))

[[ 7  2 71 44]
 [ 2 31 87 87]
 [85 44 61 38]
 [93 83 93 61]
 [55 52 18 12]
 [ 6 42 52 12]]


[[44 71  2  7]
 [87 87 31  2]
 [38 61 44 85]
 [61 93 83 93]
 [12 18 52 55]
 [12 52 42  6]]


[[ 6 42 52 12]
 [55 52 18 12]
 [93 83 93 61]
 [85 44 61 38]
 [ 2 31 87 87]
 [ 7  2 71 44]]


In [85]:
#put function helps in chnaging the values in the array

b=np.array([10,15,20,25,30,35,40,45,50])
np.put(b,[1,4],[-15,-30])   #We have to provide the index value of the array we want to replace and the new values
print(b)

#Put is a permanent operation

[ 10 -15  20  25 -30  35  40  45  50]


In [89]:
#Delete -> If we want to delete a specific item from the array

print(b)

np.delete(b,1)   #We just have to provide the index value 

[ 10 -15  20  25 -30  35  40  45  50]


array([ 10,  20,  25, -30,  35,  40,  45,  50])

#### Set Functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [90]:
#np.union1d

a=np.array([1,7,3,10,14,20])
b=np.array([12,11,8,1,10,7])

np.union1d(a,b)

array([ 1,  3,  7,  8, 10, 11, 12, 14, 20])

In [91]:
#np.intersect1d

np.intersect1d(a,b)

array([ 1,  7, 10])

In [93]:
#np.setdiff1d

np.setdiff1d(a,b)  #What is a has that b does not have

array([ 3, 14, 20])

In [95]:
#np.setxor1d

np.setxor1d(a,b)   #Shows all the elements that are present in both a and b, but not common elements

array([ 3,  8, 11, 12, 14, 20])

In [97]:
#np.in1d

np.in1d(a,b)   #It is a kind of membership operator. It will tell what items of "b" "a" is having.

C:\Users\Abhi\AppData\Local\Temp\ipykernel_19904\3872391230.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a,b)   #It is a kind of membership operator. It will tell what items of "b" "a" is having.


array([ True,  True, False,  True, False, False])

In [100]:
print(np.in1d(a,1))   #It is showing whether 1 is present in a or not. 

a[np.in1d(a,1)]    #It will now directly showing the element

[ True False False False False False]


C:\Users\Abhi\AppData\Local\Temp\ipykernel_19904\291440750.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print(np.in1d(a,1))   #It is showing whether 1 is present in a or not.
C:\Users\Abhi\AppData\Local\Temp\ipykernel_19904\291440750.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  a[np.in1d(a,1)]    #It will now directly showing the element


array([1])

In [101]:
#np.clip

print(b)

[12 11  8  1 10  7]


In [105]:
b=np.array([12,11,8,1,10,7])

np.clip(a,a_min=2,a_max=5)   #The clip function replaces all the values that are outside the range.
#For example -> our range was from 2 to 5. So, all the items that are less than 2 will be replaced by 2 and all
#the items that are greater than 5 will be replaced by 5

array([2, 5, 3, 5, 5, 5])